id: AF8C1A4AC
title: Purification of Negativity through Amitābha
type: translation
pechas:
- IA24F6F6F
- I3C464B16
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:31:36.209096
  last_modified_at: 2023-01-04 11:31:36.209111
  collections:
  - Chögyal Pakpa Lodrö Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  IA24F6F6F/DD2B: FF9D
  I3C464B16/9B12: FF9D
